PeaceLifeParty/PeaceLifeParty/Areas/Admin/Controllers/AdminController.cs
using PeaceLifeParty.Areas.Admin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PeaceLifeParty.Areas.Admin.Controllers
{
    public class AdminController : Controller
    {
        private VmMemberList model;
        public AdminController()
        {
            model = new VmMemberList();
        }
        // GET: Admin/Admin
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult LoadData()
        {

            var draw = 0;// Request.Form.GetValues("draw").FirstOrDefault();
            var start = 0;// Request.Form.GetValues("start").FirstOrDefault();
            var length = 0;// Request.Form.GetValues("length").FirstOrDefault();
            var sortColumn = "";// Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
            var sortColumnDir = "";// Request.Form.GetValues("order[0][dir]").FirstOrDefault();

            var data = model.MemberList();
            //total number of rows count     
            var recordsTotal = data.Count();
            //Returning Json Data    
            //return View(model);
            return Json(new { data = data }, JsonRequestBehavior.AllowGet); 
        }
    }
}

PeaceLifeParty/PeaceLifeParty/Areas/Admin/Views/Admin/Index.cshtml
@model PeaceLifeParty.Areas.Admin.Models.VmMemberList
           @using vEmpireSoft.PPL.Service;
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}




<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ShowGrid</title>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />

    <link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />


    <script>
 
    </script>

</head>
<body>
    <div class="container-fluid">
        <br />
        <div class="row col-lg-12" >
            <table id="demoGrid" class="table table-striped table-bordered dt-responsive nowrap" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>FirstName</th>
                        <th>Surname</th>
                        <th>AddressLine1</th>
                        <th>AddressLine2</th>
                        <th>AddressLine3</th>
                        <th>Suburb</th>
                        <th>State</th>
                        <th>PostCode</th>
                        <th>HomePhoneNumber</th>
                        <th>WorkPhoneNumber</th>
                        <th>MobileNumber</th>
                        <th>FaxNumber</th>
                        <th>Email</th>
                        <th>RegisteredDate</th>
                    </tr>
                </thead>
                <tbody>
                    @*@{
                        foreach (MemberDto entity in @Model.memberList)
                        {
                            <tr>
                                <td>
                                    @entity.Title
                                </td>
                                <td>
                                    @entity.Title
                                </td>
                            </tr>
                        }
                    }*@
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>





@section scripts{
   
        
    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js"></script>
<script>
    $(document).ready(function () {
        $("#demoGrid").DataTable({

            "processing": true, // for show progress bar
            "serverSide": true, // for process server side
            "filter": true, // this is for disable filter (search box)
            "orderMulti": false, // for disable multiple column at once
            "pageLength": 5,

            "ajax": {
                "url": '@Url.Action("LoadData", "Admin")',
                "type": "POST",
                "datatype": "json"
            },

            //"columnDefs":
            //[{
            //    "targets": [0],
            //    "visible": false,
            //    "searchable": false
            //},
            //{
            //    "targets": [7],
            //    "searchable": false,
            //    "orderable": false
            //},
            //{
            //    "targets": [8],
            //    "searchable": false,
            //    "orderable": false
            //},
            //{
            //    "targets": [9],
            //    "searchable": false,
            //    "orderable": false
            //}],

            "columns": [
                  { "data": "Title", "name": "Title", "autoWidth": true },
                  { "data": "FirstName", "name": "FirstName", "autoWidth": true },
                  { "data": "Surname", "title": "Surname", "name": "Surname", "autoWidth": true },
                  { "data": "AddressLine1", "name": "AddressLine1", "autoWidth": true },
                  { "data": "AddressLine2", "name": "AddressLine2", "autoWidth": true },
                  { "data": "AddressLine3", "name": "AddressLine3", "autoWidth": true },
                  { "data": "Suburb", "name": "Suburb", "autoWidth": true },
                  { "data": "State", "name": "State", "title": "State", "autoWidth": true },
                  { "data": "PostCode", "name": "PostCode", "autoWidth": true },
                  { "data": "HomePhoneNumber", "name": "HomePhoneNumber", "autoWidth": true },
                  { "data": "WorkPhoneNumber", "name": "WorkPhoneNumber", "autoWidth": true },
                  { "data": "MobileNumber", "name": "MobileNumber", "autoWidth": true },
                  { "data": "FaxNumber", "name": "FaxNumber", "title": "FaxNumber", "autoWidth": true },
                  { "data": "Email", "name": "Email", "autoWidth": true },
                  { "data": "RegisteredDate", "name": "RegisteredDate", "title": "RegisteredDate", "autoWidth": true },
                  //{
                  //    "render": function (data, type, full, meta)
                  //    { return '<a class="btn btn-info" href="/Admin/Index/' + full.MemberID + '">Edit</a>'; }
                  //},
                  // {
                  //     data: null, render: function (data, type, row) {
                  //         return "<a href='#' class='btn btn-danger' onclick=DeleteData('" + row.MemberID + "'); >Delete</a>";
                  //     }
                  // },

            ]

        });
    });
</script>



}  

PeaceLifeParty/PeaceLifeParty/Areas/Admin/Views/Admin/View.cshtml

@{
    ViewBag.Title = "View";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>View</h2>
